### ISSUE TITLE
Strange crash on init in server environment

### ISSUE THREAD

**Issue by magneticflux-** [shedaniel/FiberToCloth#11]
I only create the actual screen if the ModMenu entrypoint is loaded, so that doesn't cause the crash. It seems like the mod is getting loaded in the wrong classloader somehow?

The mod is loaded in the classloader `Launcher$AppClassLoader`, which has parent `Launcher$ExtClassLoader`. However, the Fabric loader hijacks the classloader with `KnotClassLoader` which has parent `KnotClassLoader$DynamicURLClassLoader` which has parent `DummyClassLoader` which finally has parent `Launcher$AppClassLoader` (the same instance as the original).

`Fiber2ClothAnnotations.configure` loads classes using the original `Launcher$AppClassLoader` which doesn't include mod classes because the Fabric loader hijacks it.

This is the error:
```
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-tree-chopper'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.minecraft.server.Main.main(Main.java:90) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "io/github/fablabsmc/fablabs/api/fiber/v1/annotation/AnnotatedSettings$Builder"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_275]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_275]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_275]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_275]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_275]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at me.shedaniel.fiber2cloth.impl.annotation.Fiber2ClothAnnotations.configure(Fiber2ClothAnnotations.java:37) ~[fiber2cloth-3.0.1@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.kt:40) ~[main/:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	... 11 more
```

**Comment by shedaniel** [comment]
I think fiber itself is loading in the AppClassLoader, is this in dev? Are you loading the class in mixin plugins or prelaunch?

**Comment by magneticflux-** [comment]
This is in dev, it appears a different error occurs in normal/prod in the linked issue:
```
[26.12 12:20:51] [Server] Caused byjava.lang.NoClassDefFoundError: me/shedaniel/fiber2cloth/api/Fiber2Cloth
[26.12 12:20:51] [Server] 	at com.skaggsm.treechoppermod.FabricTreeChopper$onInitialize$settings$1.<init>(FabricTreeChopper.java) ~[fabric-tree-chopper-0.6.0.jar:?]
[26.12 12:20:51] [Server] 	at com.skaggsm.treechoppermod.FabricTreeChopper$onInitialize$settings$1.<clinit>(FabricTreeChopper.java) ~[fabric-tree-chopper-0.6.0.jar:?]
[26.12 12:20:51] [Server] 	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.java:37) ~[fabric-tree-chopper-0.6.0.jar:?]
[26.12 12:20:51] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[customjava14.jar:?]
[26.12 12:20:51] [Server] 	... more
[26.12 12:20:51] [Server] Caused byjava.lang.ClassNotFoundException: me.shedaniel.fiber2cloth.api.Fiber2Cloth
[26.12 12:20:51] [Server] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) ~[?:?]
[26.12 12:20:51] [Server] 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
[26.12 12:20:51] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
[26.12 12:20:51] [Server] 	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[customjava14.jar:?]
[26.12 12:20:51] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
[26.12 12:20:51] [Server] 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[customjava14.jar:?]
[26.12 12:20:51] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
[26.12 12:20:51] [Server] 	at com.skaggsm.treechoppermod.FabricTreeChopper$onInitialize$settings$1.<init>(FabricTreeChopper.java) ~[fabric-tree-chopper-0.6.0.jar:?]
[26.12 12:20:51] [Server] 	at com.skaggsm.treechoppermod.FabricTreeChopper$onInitialize$settings$1.<clinit>(FabricTreeChopper.java) ~[fabric-tree-chopper-0.6.0.jar:?]
[26.12 12:20:51] [Server] 	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.java:37) ~[fabric-tree-chopper-0.6.0.jar:?]
[26.12 12:20:51] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[customjava14.jar:?]
[26.12 12:20:51] [Server] 	... more
```

As far as I know, I'm not loading anything in a mixin plugin or in prelaunch. Fiber2Cloth _does_ load a Mod Menu config screen + POJO, but that shouldn't trigger a class load since Mod Menu only enumerates entrypoints on client launches.
